id: P010395
initial_creation_type: ocr
source_metadata:
  id: bdr:W20225
  title: རྣམ་རྟོག་གིས་བཞེངས་པའི་འཇིག་རྟེན།
  author: ''
  volumes:
    e33ad08bd42b42c0b3827f4ea0b066b4:
      image_group_id: I1KG10465
      title: ''
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
