id: IEFF5CC49
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:11:33+00:00'
last_modified: '2022-06-08T13:17:00.019784+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20225
  title: རྣམ་རྟོག་གིས་བཞེངས་པའི་འཇིག་རྟེན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    88D0:
      image_group_id: I1KG10465
      title: ''
      total_pages: 118
      order: 1
      base_file: 88D0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
